export const SITE_LANGUAGE_LIST_ROUTE = '/option/languages'
export const SITE_MENU_TYPE_LIST_ROUTE = '/menu_types'
export const SITE_PAGE_SHOW_ROUTE = '/pages'
export const SITE_POST_LIST_ROUTE = '/posts'
export const SITE_PAGE_CHILDREN_PAGES_LIST_ROUTE = '/pages'